name: build-android-app
on:
  push:
    branches:
      - 'master'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up ruby env
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.2
          bundler-cache: true
 
      - name: Run tests
        working-directory: ./app/fastlane
        run: bundle exec fastlane android genYatuApk
