name: build-android-app
on:
  push:
    branches:
      - 'master'
jobs:
  build:
    runs-on: macos-latest

    strategy:
      matrix:
        node-version: [21.x]

    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/setup-java@v1
        with:
          java-version: '11'
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: |
          yarn install
      - name: Build and ship
        run: |
          yarn fastlaneAndroid:YatuApk
