name: build-android-app
on:
  push:
    branches:
      - 'master'
jobs:
  build:
    runs-on: macos-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: yarn install
      - name: Build and ship
        run: yarn fastlaneAndroid:YatuApk
